version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolioweb
    ports:
      - "3000:3000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
    # You can add volumes if needed
    # volumes:
    #   - .:/app