services:
  - type: web
    name: portfolioweb
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheck:
      type: http
      endpoint: /health
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      # Add your own additional keys below
      # - key: EMAIL_USER
      #   value: your_username
      # - key: EMAIL_PASS
      #   value: your_password